#!/bin/sh

# VARIABLES ================================================
#Change these as needed.

USER="kandrews" #current machine user

TO_BE_ARCHIVED="/home/$USER/" #path of folders to be backed up

RSYNC_USER="kraig" #server user name
RSYNC_PASS="kraig92" #server password
RSYNC_SERVER="kevinjandrews.com" #server address
RSYNC_DIR="~/backups/" #target dir for backup

ARCHIVE=$BACKUP_DIR-$THE_DATE.tar.gz # *.tar.gz name

# END VARIABLES ============================================

# CHANGE BELOW THIS LINE SHOULD NOT BE NEEDED

# BEGIN CONFIGURATION ======================================

HOME_PATH="/home/$USER/" #top dir path
TEMP_DIR="/home/$USER/tmp" #temporary storage folder

SERVER_ALL=$RSYNC_USER@$RSYNC_SERVER:$RSYNC_DIR

THE_DATE=$(date +%a-%b%d-%Y_%H-%M)

## COMMAND PATHS ##
TAR_PATH="$(which tar)"
RSYNC_PATH="$(which rsync)"

# END CONFIGURATION ========================================

START=$(date +%s) #start time of backup
echo "Backup Started: $(date)"
echo "$SERVER_ALL"
# check for $TEMP_DIR, if not created, then create
if [ ! -d "$TEMP_DIR" ]; then
	mkdir $TEMP_DIR
fi

# Get a list of files in the source dir and copy them to the
# folder $TEMP_DIR
echo "------------------------------"
cd $TO_BE_ARCHIVED # move to dir to be archived
for d in *
do 
	if [ $d != "$TEMP_DIR" ]
	then
		echo "Moving $d to $TEMP_DIR..."
		cp $d -at $TEMP_DIR # move files/folders to $TEMP_DIR
	fi
done 
echo "-------------------------------"

cd $HOME_PATH

echo "Archiving $TEMP_DIR..."
$TAR_PATH --exclude="*/log" --exclude="$TEMP_DIR" $TEMP_DIR -czf $TO_BE_ARCHIVED # create tar.gz file of the $TEMP_DIR with the appropriate excludes

echo "Sending $TO_BE_ARCHIVED to $RSYNC_USER@$RYSNC_SERVER:$RSYNC_DIR"
sshpass -p $RSYNC_PASS rsync $TO_BE_ARCHIVED $RSYNC_USER@$RYSNC_SERVER:$RSYNC_DIR

rm -rf $TEMP_DIR

END=$(date +%s)
TOTAL=$(($END - $START))
echo "Backup and transfer complete! It took $TOTAL seconds..."



