#!/bin/sh

# Variables ===========================================

#Change these to be machine specific

## Host Machine Info ##
USER="kandrews" # host machine username
TOP="/home/$USER" #top directory under user
################################

## Target server information ##
RSYNC_USER="kraig" #username
RSYNC_PASS="kraig92" #password
RSYNC_SERVER="kevinjandrews.com" #server address
RSYNC_DIR="/backups/" # target directory on server
################################

## Backup Details ##
TO_BE_ARCHIVED="$TOP/tests" #specific directory to be backed up 
NAME="Backup" #name of the the item to be sent.

# End Variables ========================================

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# Change below here at own risk
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# Begin Configuration ==================================

THE_DATE=$(date +%a-%b%d-%Y_%H-%M)

## misc vars ##
TEMP_DIR="$TOP/tmp" #temp storage folder to be made
SERVER_CREDS="$RSYNC_USER@$RSYNC_SERVER:$RSYNC_DIR" #full server data
###############

FULL_NAME=$NAME-$THE_DATE.tar.gz #full name of backup archive

## binaries ##
TAR_PATH="$(which tar)"
RSYNC_PATH="$(which rsync)"
##############

# End Configuration ====================================

# Main Script ==========================================

START=$(date +%s) #start time of backup
echo "Backup started: $(date)"
echo "----------------------------"
echo "All data in $TO_BE_ARCHIVED will be backed up"
echo "and stored to $SERVER_CREDS"
echo "----------------------------"

#create temp dir for storage
if [ ! -d "$TEMP_DIR" ]; then
	mkdir $TEMP_DIR
fi

# get a list of files in the desired dir and copy them to the 
# folder $TEMP_DIR
echo "----------------------------"
cd $TO_BE_ARCHIVED # move to the correct dir
for d in * 
do 
	if [ $d != "$TEMP_DIR" ]
	then
		echo "Moving $d to $TEMP_DIR..."
		cp $d -at $TEMP_DIR #move files/folders to $TEMP_DIR
	fi
done 
echo "-----------------------------"

cd $TOP

echo "Archiving $TEMP_DIR..."
$TAR_PATH --exclude="*/log" $TEMP_DIR -czf $FULL_NAME #archive $TEMP

echo "Sending $FULL_NAME to $SERVER_CREDS..."
sshpass -p $RSYNC_PASS rsync $FULL_NAME $SERVER_CREDS

END=$(date +%s)
TOTAL=$(($END - $START))
echo "Backup and transfer complete! It took $TOTAL seconds..."
